### PR TITLE
Simplify AKS builder usage with additional defaults.

### LINKED ISSUE #744: Creating AKS basic cluster fails cluster
the following AZ CLI command works

```
az aks create -g "sa-rg" -n "aks-cluster" --enable-managed-identity
```

I want to get the same using farmer, however I cannot get it working:

```
#r "nuget: Farmer"

open Farmer
open Farmer.Builders

let aksCluster = aks {
    name "aks-cluster"
    service_principal_use_msi
}

let deployment = arm {
    location Location.AustraliaEast
    add_resource aksCluster
}

deployment |> Deploy.execute "sa-rg" Deploy.NoParameters
```
```
Compatible version of Azure CLI 2.27.1 detected
Checking Azure CLI logged in status... you are already logged in, nothing to do.
Using subscription 'Renewtrak - Microsoft Partner Network' (26327a2b-81b3-4c10-bb84-e43c17c24178).
Creating resource group sa-rg (1/1)...
Deploying ARM template (please be patient, this can take a while)...
BAD
System.Exception: ERROR: {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'farmer-deploy-8140' is not valid according to the validation procedure. The tracking id is '9108cb2b-d689-4f4d-a81e-9ae45de8d351'. See inner errors for details.","details":[{"code":"InvalidParameter","message":"Provisioning of resource(s) for container service aks-cluster in resource group sa-rg failed. Message: {\n  \"code\": \"InvalidParameter\",\n  \"message\": \"The value of parameter dnsPrefix is invalid. Error details: DNS prefix '' is invalid. DNS prefix must contain between 1 and 54 characters. Please see https://aka.ms/aks-naming-rules for more details.. Please see https://aka.ms/aks-naming-rules for more details.\",\n  \"target\": \"dnsPrefix\"\n }. Details: "}]}}

   at Farmer.Deploy.execute(String resourceGroupName, FSharpList`1 parameters, IDeploymentSource deployment) in Farmer.dll:token 0x60035e9+0x28
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in RefEmit_InMemoryManifestModule:token 0x6000007+0x94
Stopped due to error

```

### PR DESCRIPTION
**Pull request by ninjarobot**
This PR closes #744 

The changes in this PR are as follows:

* Container Service (AKS): Simplify `aks` builder with defaults for node pool and DNS prefix.

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [x] **Tested my code** end-to-end against a live Azure subscription.
* [x] **Updated the documentation** in the docs folder for the affected changes.
* [x] **Written unit tests** against the modified code that I have made.
* [x] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [x] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

### CODE REVIEW

**Comment by francotiveron** [comment]
@ninjarobot @isaacabraham 
I did also some investigation. The arm template doesn't necessarily need the msi identity to be explicitly created. See
https://stackoverflow.com/questions/68817153/unable-to-create-azure-aks-container-service-with-managed-identity-using-arm-tem
I tried forking the farmer repo and tweaking the generated arm template just before submitting it yo az CLI, replacing the generate one with that in the SO response, and it worked.
It would be good if this is also the behaviour of farmer (I mean not require to create a user defined identity but work with a system provided one)

File: src/Farmer/Builders/Builders.ContainerService.fs [hunk 1]
```diff
@@ -53,11 +65,16 @@ type AksConfig =
...
+              DnsPrefix =
+                  if String.IsNullOrWhiteSpace this.DnsPrefix then
+                      $"{this.Name.Value}-%x{this.Name.Value.GetHashCode()}"
+                  else this.DnsPrefix
               EnableRBAC = this.EnableRBAC
               Identity = this.Identity
               AgentPoolProfiles =
-                this.AgentPools
+                match this.AgentPools with
+                | [] -> [ { AgentPoolConfig.Default with Count = 3 } ]
```
Comment (isaacabraham) [inline src/Farmer/Builders/Builders.ContainerService.fs:76]: Formatting - can you move both handlers to a newline and indent.

File: src/Farmer/Builders/Builders.ContainerService.fs [hunk 2]
```diff
@@ -17,7 +17,19 @@ type AgentPoolConfig =
       VmSize : VMSize
       VirtualNetworkName : ResourceName option
       SubnetName : ResourceName option }
-
+    static member Default = {
+            Name = ResourceName.Empty
```
Comment (isaacabraham) [inline src/Farmer/Builders/Builders.ContainerService.fs:21]: Unless GH is showing wrongly here, this is double indented (8 instead of 4 chars).

File: docs/content/api-overview/resources/aks-cluster.md [hunk 3]
```diff
@@ -78,12 +90,11 @@ let myAks = aks {
         }
     ]
     linux_profile "aksuser" "public-key-here"
-    service_principal_client_id "some-spn-client-id"
+    service_principal_use_msi
```
Comment (isaacabraham) [inline docs/content/api-overview/resources/aks-cluster.md:93]: It doesn't like this this is a "new" keyboard but if it is, consider parameterisation of it with e.g. a boolean, which makes it easier for programmatically working with it.

**Review by isaacabraham — APPROVED** [review]
Approve with minor formatting changes.

File: docs/content/api-overview/resources/aks-cluster.md (hunk 3 above)
Comment (ninjarobot) [reply docs/content/api-overview/resources/aks-cluster.md:93]: It's was added a while back after the AKS team started supporting MSI for the cluster, but I think a cleanup item would make sense to deprecate these two and make one operation that makes it clear you can **either** set the SP client ID or use MSI.

File: src/Farmer/Builders/Builders.ContainerService.fs (hunk 2 above)
Comment (ninjarobot) [reply src/Farmer/Builders/Builders.ContainerService.fs:21]: It was - fixed it while applying the same formatting used elsewhere for records.

File: src/Farmer/Builders/Builders.ContainerService.fs (hunk 1 above)
Comment (ninjarobot) [reply src/Farmer/Builders/Builders.ContainerService.fs:76]: Yes, done.
