### PR TITLE
put quotes around zip_deploy path when passing to `az`

### LINKED ISSUE #472: zip_deploy does not support paths with spaces
Currently, the following declaration will fail during post-deploy
```fs
webapp{
    // ...
    zip_deploy "../My WebApp/publish.zip" // Note the space in the path
}
```

This, I believe, is because the src path is not quoted when passed to `az`:

```fs
// Taken from Farmer/Deploy.fs:master:L120-122
let private zipDeploy command appName getZipPath resourceGroup =
        let packageFilename = getZipPath deployFolder
        az (sprintf """%s deployment source config-zip --resource-group "%s" --name "%s" --src %s""" command resourceGroup appName packageFilename)
```

### PR DESCRIPTION
**Pull request by TheRSP**
This PR closes #472

The changes in this PR are as follows:

* allow spaces in zip-deploy paths

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [x] **Tested my code** end-to-end against a live Azure subscription.
* [x] **Updated the documentation** in the docs folder for the affected changes.
* [x] **Written unit tests** against the modified code that I have made.
* [x] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [x] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:

### CODE REVIEW

File: src/Farmer/Deploy.fs [hunk 1]
```diff
@@ -117,13 +117,13 @@ module Az =
     // The what-if operation doesn't make any changes to existing resources. Instead, it predicts the changes if the specified template is deployed.
     let whatIf resourceGroup deploymentName templateFilename parameters = deployOrValidate WhatIf resourceGroup deploymentName templateFilename parameters
     /// Generic function for ZipDeploy using custom command (based on application type)
-    let private zipDeploy command appName getZipPath resourceGroup =
-        let packageFilename = getZipPath deployFolder
+    let internal zipDeploy az command appName getZipPath resourceGroup =
```
Comment (isaacabraham) [inline src/Farmer/Deploy.fs:120]: Is this extra parameter to allow "mocking" or injecting the actual `az` command? That's an interesting approach :-) I think it might be better to simply have the `zipDeploy` function return a string and have the callers pipe it into `az`.

**Comment by isaacabraham** [comment]
I've done some end-to-end tests on this. I think in the end an automated test wasn't worth the effort so I've reverted that and committed. If you're happy with this, let me know and I'll merge in.

**Comment by TheRSP** [comment]
Yeah, I agree that the test was a bit forced. Looks good to me 👍

**Comment by isaacabraham** [comment]
Thanks for this.
