### PR TITLE
Fix missing AutoSwapSlotName in json output.

### LINKED ISSUE #836: Bug: WebApp slots: AutoSwapSlotName is not added to json output
There is a setting for AutoSwapSlotName in the SlotBuilder but it is never used when writing the template json output.

My expectation is that is should be written to the json output so AutoSwapSlotName can be configured.

I have made a fix locally and it works fine to set the AutoSwapSlotName and the deployed slot will correctly autoswap in azure. The only caveat seems to be that if you then remove AutoSwapSlotName from the template the setting will not switch back to AutoSwap enabled = Off, i.e. to disable the feature I had to manually turn it off in the azure portal. 
But this seems like a bug or limitation in ARM for this specific setting.

I'll submit a PR with my fix.

### PR DESCRIPTION
**Pull request by viktorvan**
This PR closes #836

The changes in this PR are as follows:

* Add autoSwapSlotName to JsonModel for WebApp.

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [x] **Tested my code** end-to-end against a live Azure subscription.
* [ ] **Updated the documentation** in the docs folder for the affected changes.
* [x] **Written unit tests** against the modified code that I have made.
* [x] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [x] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:
* The SlotBuilder does not seem to be documented.

### CODE REVIEW

File: src/Farmer/Arm/Web.fs [hunk 1]
```diff
@@ -287,6 +287,10 @@ type Site =
                                            supportCredentials = credentials |> Option.toNullable |})
                             |> Option.toObj
                            healthCheckPath = this.HealthCheckPath |> Option.toObj
+                           autoSwapSlotName =
+                               match this.AutoSwapSlotName with
```
Comment (isaacabraham) [inline src/Farmer/Arm/Web.fs:291]: Replace this match with `Option.toObj`

**Review by isaacabraham — COMMENTED** [review]
Tiny fix and this can then go in. Interesting that there's no docs on this apparently.
